export interface AllahName {
  number: number;
  name: string;
  transliteration: string;
  meaning: string;
}

export const asmaUlHusna: AllahName[] = [
  { number: 1, name: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Most Gracious" },
  { number: 2, name: "الرَّحِيمُ", transliteration: "Ar-Raheem", meaning: "The Most Merciful" },
  { number: 3, name: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "The King" },
  { number: 4, name: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy" },
  { number: 5, name: "السَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { number: 6, name: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Granter of Security" },
  { number: 7, name: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian" },
  { number: 8, name: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty" },
  { number: 9, name: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller" },
  { number: 10, name: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme" },
  { number: 11, name: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { number: 12, name: "الْبَارِئُ", transliteration: "Al-Bari", meaning: "The Originator" },
  { number: 13, name: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { number: 14, name: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Forgiver" },
  { number: 15, name: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer" },
  { number: 16, name: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { number: 17, name: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider" },
  { number: 18, name: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { number: 19, name: "اَلْعَلِيْمُ", transliteration: "Al-Alim", meaning: "The All-Knowing" },
  { number: 20, name: "الْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Withholder" },
  { number: 21, name: "الْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Extender" },
  { number: 22, name: "الْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Reducer" },
  { number: 23, name: "الرَّافِعُ", transliteration: "Ar-Rafi", meaning: "The Exalter" },
  { number: 24, name: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Honourer" },
  { number: 25, name: "المُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humiliator" },
  { number: 26, name: "السَّمِيعُ", transliteration: "As-Sami", meaning: "The All-Hearing" },
  { number: 27, name: "الْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { number: 28, name: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge" },
  { number: 29, name: "الْعَدْلُ", transliteration: "Al-Adl", meaning: "The Just" },
  { number: 30, name: "اللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle One" },
  { number: 31, name: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware" },
  { number: 32, name: "الْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing" },
  { number: 33, name: "الْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent" },
  { number: 34, name: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The All-Forgiving" },
  { number: 35, name: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative" },
  { number: 36, name: "الْعَلِيُّ", transliteration: "Al-Ali", meaning: "The Most High" },
  { number: 37, name: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Most Great" },
  { number: 38, name: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver" },
  { number: 39, name: "المُقيِت", transliteration: "Al-Muqit", meaning: "The Sustainer" },
  { number: 40, name: "اَلْحسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner" },
  { number: 41, name: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Majestic" },
  { number: 42, name: "الْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous" },
  { number: 43, name: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful" },
  { number: 44, name: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive" },
  { number: 45, name: "الْوَاسِعُ", transliteration: "Al-Wasi", meaning: "The All-Encompassing" },
  { number: 46, name: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The All-Wise" },
  { number: 47, name: "الْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving One" },
  { number: 48, name: "الْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Most Glorious" },
  { number: 49, name: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector" },
  { number: 50, name: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness" },
  { number: 51, name: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { number: 52, name: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee" },
  { number: 53, name: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Strong" },
  { number: 54, name: "الْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm" },
  { number: 55, name: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protecting Friend" },
  { number: 56, name: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy" },
  { number: 57, name: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The Counter" },
  { number: 58, name: "الْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator" },
  { number: 59, name: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer" },
  { number: 60, name: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { number: 61, name: "اَلْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Creator of Death" },
  { number: 62, name: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever Living" },
  { number: 63, name: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Subsisting" },
  { number: 64, name: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Finder" },
  { number: 65, name: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Noble" },
  { number: 66, name: "الْواحِدُ", transliteration: "Al-Wahid", meaning: "The One" },
  { number: 67, name: "اَلاَحَدُ", transliteration: "Al-Ahad", meaning: "The Unique" },
  { number: 68, name: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal" },
  { number: 69, name: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Able" },
  { number: 70, name: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Powerful" },
  { number: 71, name: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter" },
  { number: 72, name: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { number: 73, name: "الأوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { number: 74, name: "الآخِرُ", transliteration: "Al-Akhir", meaning: "The Last" },
  { number: 75, name: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest" },
  { number: 76, name: "الْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden" },
  { number: 77, name: "الْوَالِي", transliteration: "Al-Wali", meaning: "The Governor" },
  { number: 78, name: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted" },
  { number: 79, name: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness" },
  { number: 80, name: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Acceptor of Repentance" },
  { number: 81, name: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { number: 82, name: "العَفُوُّ", transliteration: "Al-Afuww", meaning: "The Pardoner" },
  { number: 83, name: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Compassionate" },
  { number: 84, name: "مَالِكُ الْمُلْكِ", transliteration: "Malik-ul-Mulk", meaning: "Owner of Sovereignty" },
  { number: 85, name: "ذُوالْجَلاَلِ وَالإكْرَامِ", transliteration: "Dhul-Jalali-wal-Ikram", meaning: "Lord of Majesty and Generosity" },
  { number: 86, name: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { number: 87, name: "الْجَامِعُ", transliteration: "Al-Jami", meaning: "The Gatherer" },
  { number: 88, name: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "The Self-Sufficient" },
  { number: 89, name: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { number: 90, name: "اَلْمَانِعُ", transliteration: "Al-Mani", meaning: "The Preventer" },
  { number: 91, name: "الضَّارَّ", transliteration: "Ad-Darr", meaning: "The Distresser" },
  { number: 92, name: "النَّافِعُ", transliteration: "An-Nafi", meaning: "The Propitious" },
  { number: 93, name: "النُّورُ", transliteration: "An-Nur", meaning: "The Light" },
  { number: 94, name: "الْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { number: 95, name: "الْبَدِيعُ", transliteration: "Al-Badi", meaning: "The Incomparable" },
  { number: 96, name: "اَلْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting" },
  { number: 97, name: "الْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor" },
  { number: 98, name: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path" },
  { number: 99, name: "الصَّبُورُ", transliteration: "As-Sabur", meaning: "The Patient" },
];
